import fs from "fs/promises";
import path from "path";
import { notFound } from "next/navigation";
import Link from "next/link";
import { getInsightBySlug, getInsights } from "@/lib/content";
import InsightArticleContent from "@/components/public/InsightArticleContent";
import NewsletterSignup from "@/components/public/NewsletterSignup";
import InsightListRow from "@/components/public/InsightListRow";
import type { Metadata } from "next";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const insight = await getInsightBySlug(slug);
  if (!insight) return { title: "Not Found" };

  const url = `https://pedroripper.com/insights/${insight.slug}`;
  return {
    title: insight.title,
    description: insight.excerpt,
    alternates: { canonical: url },
    ...(insight.visible === false
      ? { robots: { index: false, follow: false } }
      : {}),
    openGraph: {
      title: insight.title,
      description: insight.excerpt,
      url,
      siteName: "Pedro Ripper",
      type: "article",
      ...(insight.coverImage
        ? { images: [{ url: insight.coverImage, alt: insight.title }] }
        : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: insight.title,
      description: insight.excerpt,
      ...(insight.coverImage ? { images: [insight.coverImage] } : {}),
    },
  };
}

/**
 * Reads the pre-converted, CSS-scoped article fragment (full body HTML)
 * generated by scripts/convert-article.mjs. Returns null when the slug has
 * no standalone article (then we fall back to markdown rendering).
 * Only called after the slug is validated against the insights data.
 */
async function getArticleFragment(slug: string): Promise<string | null> {
  try {
    return await fs.readFile(
      path.join(process.cwd(), "src", "content", "articles", `${slug}.html`),
      "utf-8"
    );
  } catch {
    return null;
  }
}

export default async function InsightArticlePage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const insight = await getInsightBySlug(slug);

  if (!insight) notFound();

  // Article JSON-LD — author/publisher anchored to the site's Person entity
  const articleLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    "@id": `https://pedroripper.com/insights/${insight.slug}#article`,
    headline: insight.title,
    description: insight.excerpt,
    inLanguage: insight.language === "pt" ? "pt-BR" : "en",
    datePublished: insight.date,
    dateModified: insight.updatedAt?.slice(0, 10) || insight.date,
    ...(insight.coverImage
      ? { image: `https://pedroripper.com${insight.coverImage}` }
      : {}),
    author: {
      "@type": "Person",
      "@id": "https://pedroripper.com/#pedro-ripper",
      name: "Pedro Ripper",
      url: "https://pedroripper.com",
    },
    publisher: {
      "@type": "Person",
      "@id": "https://pedroripper.com/#pedro-ripper",
      name: "Pedro Ripper",
    },
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": `https://pedroripper.com/insights/${insight.slug}`,
    },
  };

  const fragment = await getArticleFragment(slug);

  // Related articles — shared tags first, newest fill the rest
  const others = (await getInsights()).filter((i) => i.slug !== slug);
  const sharesTag = (i: (typeof others)[number]) =>
    i.tags?.some((t) => insight.tags?.includes(t));
  const related = [...others.filter(sharesTag), ...others.filter((i) => !sharesTag(i))].slice(0, 3);

  const relatedBlock =
    related.length > 0 ? (
      <div className="max-w-[1200px] mx-auto px-5 md:px-12 mt-12">
        <div className="flex items-center gap-3 mb-2">
          <span className="w-7 h-[1.5px] bg-[var(--color-accent)]" />
          <span className="text-[0.72rem] font-semibold tracking-[0.18em] text-[var(--color-accent)] uppercase">
            Leia também
          </span>
        </div>
        <div className="flex flex-col">
          {related.map((item, i) => (
            <InsightListRow key={item.id} item={item} topBorder={i > 0} />
          ))}
        </div>
      </div>
    ) : null;

  const backLink = (
    <Link
      href="/insights"
      className="inline-flex items-center gap-2 text-[0.85rem] font-medium text-[var(--color-text-secondary)] hover:text-[var(--color-accent)] transition-colors duration-[400ms]"
    >
      <svg
        width="16"
        height="16"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M19 12H5M12 19l-7-7 7-7" />
      </svg>
      Back to Insights
    </Link>
  );

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleLd) }}
      />
      {fragment ? (
        /* Native server-rendered article body — fully crawlable HTML */
        <div className="pt-[96px] pb-[40px]">
          <div className="max-w-[1200px] mx-auto px-5 md:px-12">{backLink}</div>
          <div
            className="article-doc"
            dangerouslySetInnerHTML={{ __html: fragment }}
          />
          <div className="max-w-[640px] mx-auto px-5 md:px-0 mt-4 mb-10">
            <NewsletterSignup />
          </div>
          {relatedBlock}
        </div>
      ) : (
        <article className="pt-[120px] pb-[120px]">
          <div className="max-w-[720px] mx-auto px-5 md:px-12">
            <div className="mb-12">{backLink}</div>
            <InsightArticleContent insight={insight} />
          </div>
          {relatedBlock}
        </article>
      )}
    </>
  );
}
